execute pathogen#infect()
filetype plugin indent on
syntax on
inoremap jj <Esc>

set rtp+=/usr/local/lib/python2.7/dist-packages/powerline/bindings/vim/
" Always show statusline
set laststatus=2
" Use 256 colours (Use this setting only if your terminal supports 256 colours)
set t_Co=256

colorscheme zenburn
:hi Normal          ctermfg=none ctermbg=none
:hi EndOfBuffer     ctermfg=none ctermbg=none
let g:airline_theme='angr'
let g:airline_powerline_fonts = 1

map <Esc>[7~ <Home>
map <Esc>[8~ <End>

imap <Esc>[7~ <Home>
imap <Esc>[8~ <End>
